# Generated by Django 6.0.7 on 2026-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین پال'), ('test', 'درگاه آزمایشی')], max_length=30, verbose_name='درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
    ]
