# Generated by Django 6.0.7 on 2026-08-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='staff_manage',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='staff_product',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='staff_user',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='stock_user',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن'), ('n', 'نمیخواهم مشخص کنم')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
    ]
