# Generated by Django 6.0.7 on 2026-08-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending_payment', 'درانتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'درحال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending_payment', max_length=20, verbose_name='وضعیت سفارش')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='نام گیرنده')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('plaque', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('total_amount', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, verbose_name='نام محصول')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='کد کالا')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_price', models.PositiveBigIntegerField(verbose_name='قیمت واحد')),
                ('total_price', models.PositiveBigIntegerField(verbose_name='قیمت کل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم سفارش',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان آدرس')),
                ('recipient_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('plaque', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('is_default', models.BooleanField(default=False, verbose_name='آدرس پیشفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس',
                'ordering': ['-is_default', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='unique_default_address_per_user')],
            },
        ),
    ]
