# Generated by Django 6.0.7 on 2026-08-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'درانتظار پرداخت'), ('paid', 'پرداخت شده'), ('processing', 'درحال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('expired', 'منقضی شده')], default='pending_payment', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
