# Generated by Django 6.0.7 on 2026-09-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expires_at',
        ),
    ]
