# Generated by Django 6.0.7 on 2026-09-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'درانتظار پرداخت'), ('paid', 'پرداخت شده'), ('completed', 'تکمیل شده'), ('processing', 'درحال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending_payment', max_length=20, verbose_name='وضعیت سفارش'),
        ),
    ]
