# Generated by Django 6.0.7 on 2026-09-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی رزرو شده'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی رزرو شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='در دسترس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='قابل فروش'),
        ),
    ]
